#!/bin/bash -e +x

func="$1"

if [ "$func" == "" ] || [ "$func" == "--help" ]; then
  echo "The API allows you to import locale files, download locale files or interact in other ways with the localization data stored in Translized for your account.

Usage:
translized [command]

Available Commands:
init                    Configure your Translized client
download                Download translation changes
upload                  Upload translation changes";
exit 1
fi;

if [ "$func" != "download" ] && [ "$func" != "upload" ] && [ "$func" != "init" ]; then
  echo "Run 'translized --help' for usage.";
  echo "Error: unknown command "$func" for translized.";
  exit 1
fi;

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# Init
if [ "$func" == "init" ]; then
ruby $SCRIPT_DIR/init/init.rb
fi;

# Download
if [ "$func" == "download" ]; then
ruby $SCRIPT_DIR/download/download.rb
fi;

# Upload
if [ "$func" == "upload" ]; then
overrideTranslations="false"
newKeysTag="-"
updatedKeysTag="-"
shift 1
while getopts o:n:u: flag
do
    case "${flag}" in
        o) overrideTranslations=${OPTARG};;
        n) newKeysTag=${OPTARG};;
        u) updatedKeysTag=${OPTARG};;
    esac
done
ruby $SCRIPT_DIR/upload/upload.rb $overrideTranslations $newKeysTag $updatedKeysTag
fi;